# O bloco finally é executado toda vez que um bloco try é executado, mesmo que uma exceção seja lançada e não seja capturada por um bloco except. Isso significa que o código dentro do bloco finally será executado, independentemente do resultado do bloco try. Um uso comum do bloco finally é garantir que recursos, como arquivos abertos, sejam fechados corretamente após o uso, mesmo que ocorram exceções durante a execução do código. Dessa forma, o bloco finally pode ser utilizado para realizar ações de limpeza ou finalização, independentemente de ocorrerem exceções durante a execução do programa.